<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KabupatenKota;

class KabupatenKotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kabupatenKota = [
            // Aceh
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Barat'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Besar'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Jaya'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Selatan'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Singkil'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Tamiang'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Tengah'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Tenggara'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Timur'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kabupaten Aceh Utara'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kota Banda Aceh'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kota Langsa'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kota Lhokseumawe'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kota Sabang'],
            ['id_provinsi' => 1, 'nama_kabupaten_kota' => 'Kota Subulussalam'],

            // Sumatera Utara
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Asahan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Batubara'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Dairi'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Deli Serdang'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Humbang Hasundutan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Karo'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Labuhanbatu'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Labuhanbatu Selatan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Labuhanbatu Utara'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Langkat'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Mandailing Natal'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Nias'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Nias Barat'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Nias Selatan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Nias Utara'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Padang Lawas'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Padang Lawas Utara'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Pakpak Bharat'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Samosir'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Serdang Bedagai'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Simalungun'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Tapanuli Selatan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Tapanuli Tengah'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Tapanuli Utara'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kabupaten Toba'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Binjai'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Gunungsitoli'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Medan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Padangsidempuan'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Pematangsiantar'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Sibolga'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Tanjungbalai'],
            ['id_provinsi' => 2, 'nama_kabupaten_kota' => 'Kota Tebing Tinggi'],

            // Sumatera Barat
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Agam'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Dharmasraya'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Mentawai'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Lima Puluh Kota'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Padang Pariaman'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Pasaman'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Pasaman Barat'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Pesisir Selatan'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Sijunjung'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Solok'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Solok Selatan'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kabupaten Tanah Datar'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Bukittinggi'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Padang'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Padangpanjang'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Pariaman'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Payakumbuh'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Sawahlunto'],
            ['id_provinsi' => 3, 'nama_kabupaten_kota' => 'Kota Solok'],

            // Riau
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Bengkalis'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Indragiri Hilir'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Indragiri Hulu'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Kampar'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Meranti'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Kuantan Singingi'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Pelalawan'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Rokan Hilir'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Rokan Hulu'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kabupaten Siak'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kota Dumai'],
            ['id_provinsi' => 4, 'nama_kabupaten_kota' => 'Kota Pekanbaru'],

            // Kepulauan Riau
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kabupaten Bintan'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kabupaten Karimun'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Anambas'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kabupaten Lingga'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kabupaten Natuna'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kota Batam'],
            ['id_provinsi' => 5, 'nama_kabupaten_kota' => 'Kota Tanjungpinang'],

            // Jambi
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Batanghari'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Bungo'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Kerinci'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Merangin'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Muaro Jambi'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Sarolangun'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Tanjung Jabung Barat'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Tanjung Jabung Timur'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kabupaten Tebo'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kota Jambi'],
            ['id_provinsi' => 6, 'nama_kabupaten_kota' => 'Kota Sungai Penuh'],

            // Sumatera Selatan
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Banyuasin'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Empat Lawang'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Lahat'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Muara Enim'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Musi Banyuasin'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Musi Rawas'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Musi Rawas Utara'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Ogan Ilir'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Ogan Komering Ilir'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Ogan Komering Ulu'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Ogan Komering Ulu Selatan'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kabupaten Ogan Komering Ulu Timur'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kota Lubuklinggau'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kota Pagar Alam'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kota Palembang'],
            ['id_provinsi' => 7, 'nama_kabupaten_kota' => 'Kota Prabumulih'],

            // Bangka Belitung
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Bangka'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Bangka Barat'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Bangka Selatan'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Bangka Tengah'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Belitung'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kabupaten Belitung Timur'],
            ['id_provinsi' => 8, 'nama_kabupaten_kota' => 'Kota Pangkalpinang'],

            // Bengkulu
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Bengkulu Selatan'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Bengkulu Tengah'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Bengkulu Utara'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Kaur'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Kepahiang'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Lebong'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Mukomuko'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Rejang Lebong'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kabupaten Seluma'],
            ['id_provinsi' => 9, 'nama_kabupaten_kota' => 'Kota Bengkulu'],

            // Lampung
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Lampung Barat'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Lampung Selatan'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Lampung Tengah'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Lampung Timur'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Lampung Utara'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Mesuji'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Pesawaran'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Pesisir Barat'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Pringsewu'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Tanggamus'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Tulang Bawang'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Tulang Bawang Barat'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kabupaten Way Kanan'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kota Bandar Lampung'],
            ['id_provinsi' => 10, 'nama_kabupaten_kota' => 'Kota Metro'],

            // DKI Jakarta
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Seribu'],
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kota Administrasi Jakarta Barat'],
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kota Administrasi Jakarta Pusat'],
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kota Administrasi Jakarta Selatan'],
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kota Administrasi Jakarta Timur'],
            ['id_provinsi' => 11, 'nama_kabupaten_kota' => 'Kota Administrasi Jakarta Utara'],

            // Banten
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kabupaten Lebak'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kabupaten Pandeglang'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kabupaten Serang'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kabupaten Tangerang'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kota Cilegon'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kota Serang'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kota Tangerang'],
            ['id_provinsi' => 12, 'nama_kabupaten_kota' => 'Kota Tangerang Selatan'],

            // Jawa Barat
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Bandung'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Bandung Barat'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Bekasi'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Bogor'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Ciamis'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Cianjur'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Cirebon'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Garut'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Indramayu'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Karawang'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Kuningan'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Majalengka'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Pangandaran'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Purwakarta'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Subang'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Sukabumi'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Sumedang'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kabupaten Tasikmalaya'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Bandung'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Banjar'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Bekasi'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Bogor'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Cimahi'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Cirebon'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Depok'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Sukabumi'],
            ['id_provinsi' => 13, 'nama_kabupaten_kota' => 'Kota Tasikmalaya'],

            // DI Yogyakarta
            ['id_provinsi' => 15, 'nama_kabupaten_kota' => 'Kabupaten Bantul'],
            ['id_provinsi' => 15, 'nama_kabupaten_kota' => 'Kabupaten Gunung Kidul'],
            ['id_provinsi' => 15, 'nama_kabupaten_kota' => 'Kabupaten Kulon Progo'],
            ['id_provinsi' => 15, 'nama_kabupaten_kota' => 'Kabupaten Sleman'],
            ['id_provinsi' => 15, 'nama_kabupaten_kota' => 'Kota Yogyakarta'],

            // Jawa Timur
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Banyuwangi'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Bondowoso'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Gresik'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Jember'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Jombang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Kediri'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Lamongan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Lumajang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Madiun'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Magetan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Malang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Mojokerto'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Nganjuk'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Ngawi'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pacitan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pamekasan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pasuruan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Ponorogo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Probolinggo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Sampang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Sidoarjo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Situbondo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Sumenep'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Trenggalek'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Tuban'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Tulungagung'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Batu'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Blitar'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Kediri'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Madiun'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Malang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Mojokerto'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Pasuruan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Probolinggo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Surabaya'],


            // Jawa Tengah
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Banjarnegara'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Banyumas'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Batang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Blora'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Boyolali'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Brebes'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Cilacap'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Demak'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Grobogan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Jepara'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Karanganyar'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Kebumen'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Kendal'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Klaten'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Kudus'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Magelang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pati'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pekalongan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Pemalang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Purbalingga'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Purworejo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Rembang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Semarang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Sragen'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Sukoharjo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Tegal'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Temanggung'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Wonogiri'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kabupaten Wonosobo'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Magelang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Pekalongan'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Salatiga'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Semarang'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Surakarta'],
            ['id_provinsi' => 16, 'nama_kabupaten_kota' => 'Kota Tegal'],

            // Bali
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Badung'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Bangli'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Buleleng'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Gianyar'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Jembrana'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Karangasem'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Klungkung'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kabupaten Tabanan'],
            ['id_provinsi' => 17, 'nama_kabupaten_kota' => 'Kota Denpasar'],

            // Nusa Tenggara Barat
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Bima'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Dompu'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Lombok Barat'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Lombok Tengah'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Lombok Timur'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Lombok Utara'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Sumbawa'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kabupaten Sumbawa Barat'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kota Bima'],
            ['id_provinsi' => 18, 'nama_kabupaten_kota' => 'Kota Mataram'],

            // Nusa Tenggara Timur
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Alor'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Belu'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Ende'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Flores Timur'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Kupang'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Lembata'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Malaka'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Manggarai'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Manggarai Barat'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Manggarai Timur'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Ngada'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Nagekeo'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Rote Ndao'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sabu Raijua'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sikka'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sumba Barat'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sumba Barat Daya'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sumba Tengah'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Sumba Timur'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Timor Tengah Selatan'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kabupaten Timor Tengah Utara'],
            ['id_provinsi' => 19, 'nama_kabupaten_kota' => 'Kota Kupang'],

            // Kalimantan Barat
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Bengkayang'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Kapuas Hulu'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Kayong Utara'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Ketapang'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Kubu Raya'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Landak'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Melawi'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Mempawah'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Sambas'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Sanggau'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Sekadau'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kabupaten Sintang'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kota Pontianak'],
            ['id_provinsi' => 20, 'nama_kabupaten_kota' => 'Kota Singkawang'],

            // Kalimantan Tengah
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Barito Selatan'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Barito Timur'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Barito Utara'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Gunung Mas'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Kapuas'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Katingan'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Kotawaringin Barat'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Kotawaringin Timur'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Lamandau'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Murung Raya'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Pulang Pisau'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Seruyan'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kabupaten Sukamara'],
            ['id_provinsi' => 21, 'nama_kabupaten_kota' => 'Kota Palangka Raya'],

            // Kalimantan Selatan
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Balangan'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Banjar'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Barito Kuala'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Hulu Sungai Selatan'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Hulu Sungai Tengah'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Hulu Sungai Utara'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Kotabaru'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Tabalong'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Tanah Bumbu'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Tanah Laut'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kabupaten Tapin'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kota Banjarbaru'],
            ['id_provinsi' => 22, 'nama_kabupaten_kota' => 'Kota Banjarmasin'],

            // Kalimantan Timur
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Berau'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Kutai Barat'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Kutai Kartanegara'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Kutai Timur'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Mahakam Ulu'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Paser'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kabupaten Penajam Paser Utara'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kota Balikpapan'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kota Bontang'],
            ['id_provinsi' => 23, 'nama_kabupaten_kota' => 'Kota Samarinda'],

            // Kalimantan Utara
            ['id_provinsi' => 24, 'nama_kabupaten_kota' => 'Kabupaten Bulungan'],
            ['id_provinsi' => 24, 'nama_kabupaten_kota' => 'Kabupaten Malinau'],
            ['id_provinsi' => 24, 'nama_kabupaten_kota' => 'Kabupaten Nunukan'],
            ['id_provinsi' => 24, 'nama_kabupaten_kota' => 'Kabupaten Tana Tidung'],
            ['id_provinsi' => 24, 'nama_kabupaten_kota' => 'Kota Tarakan'],

            // Sulawesi Utara
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Selatan'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Timur'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Utara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Sangihe'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Talaud'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Selatan'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Tenggara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Utara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Bitung'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Kotamobagu'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Manado'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Tomohon'],

            // Gorontalo
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Boalemo'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Bone Bolango'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Gorontalo'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Gorontalo Utara'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Pohuwato'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kota Gorontalo'],

            // Sulawesi Tengah
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai Kepulauan'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai Laut'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Buol'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Donggala'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Morowali'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Morowali Utara'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Parigi Moutong'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Poso'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Sigi'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Tojo Una-Una'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Tolitoli'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kota Palu'],

            // Sulawesi Barat
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Majene'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamasa'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamuju'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamuju Tengah'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Pasangkayu'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Polewali Mandar'],

            // Sulawesi Selatan
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bantaeng'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Barru'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bone'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bulukumba'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Enrekang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Gowa'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Jeneponto'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Selayar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu Timur'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu Utara'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Maros'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Pangkajene dan Kepulauan'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Pinrang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Sidenreng Rappang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Sinjai'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Soppeng'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Takalar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Tana Toraja'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Toraja Utara'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Wajo'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Makassar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Palopo'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Parepare'],

            // Sulawesi Tenggara
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Bombana'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Selatan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Tengah'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka Timur'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Kepulauan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Selatan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Muna'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Muna Barat'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Wakatobi'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kota Baubau'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kota Kendari'],

            // Sulawesi Utara
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Selatan'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Timur'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Bolaang Mongondow Utara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Sangihe'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Talaud'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Selatan'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Tenggara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kabupaten Minahasa Utara'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Bitung'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Kotamobagu'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Manado'],
            ['id_provinsi' => 25, 'nama_kabupaten_kota' => 'Kota Tomohon'],

            // Gorontalo
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Boalemo'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Bone Bolango'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Gorontalo'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Gorontalo Utara'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kabupaten Pohuwato'],
            ['id_provinsi' => 26, 'nama_kabupaten_kota' => 'Kota Gorontalo'],

            // Sulawesi Tengah
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai Kepulauan'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Banggai Laut'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Buol'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Donggala'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Morowali'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Morowali Utara'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Parigi Moutong'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Poso'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Sigi'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Tojo Una-Una'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kabupaten Tolitoli'],
            ['id_provinsi' => 27, 'nama_kabupaten_kota' => 'Kota Palu'],

            // Sulawesi Barat
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Majene'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamasa'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamuju'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Mamuju Tengah'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Pasangkayu'],
            ['id_provinsi' => 28, 'nama_kabupaten_kota' => 'Kabupaten Polewali Mandar'],

            // Sulawesi Selatan
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bantaeng'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Barru'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bone'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Bulukumba'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Enrekang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Gowa'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Jeneponto'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Selayar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu Timur'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Luwu Utara'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Maros'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Pangkajene dan Kepulauan'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Pinrang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Sidenreng Rappang'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Sinjai'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Soppeng'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Takalar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Tana Toraja'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Toraja Utara'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kabupaten Wajo'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Makassar'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Palopo'],
            ['id_provinsi' => 29, 'nama_kabupaten_kota' => 'Kota Parepare'],

            // Sulawesi Tenggara
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Bombana'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Selatan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Tengah'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Buton Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka Timur'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Kolaka Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Kepulauan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Selatan'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Konawe Utara'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Muna'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Muna Barat'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kabupaten Wakatobi'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kota Baubau'],
            ['id_provinsi' => 30, 'nama_kabupaten_kota' => 'Kota Kendari'],

            // Maluku
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Buru'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Buru Selatan'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Aru'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Maluku Barat Daya'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Maluku Tengah'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Maluku Tenggara'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Seram Bagian Barat'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kabupaten Seram Bagian Timur'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kota Ambon'],
            ['id_provinsi' => 31, 'nama_kabupaten_kota' => 'Kota Tual'],

            // Maluku Utara
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Halmahera Barat'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Halmahera Selatan'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Halmahera Tengah'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Halmahera Timur'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Halmahera Utara'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Sula'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Pulau Morotai'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kabupaten Pulau Taliabu'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kota Ternate'],
            ['id_provinsi' => 32, 'nama_kabupaten_kota' => 'Kota Tidore Kepulauan'],

            // Papua Barat
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Fakfak'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Kaimana'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Manokwari'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Manokwari Selatan'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Pegunungan Arfak'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Sorong'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Sorong Selatan'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Teluk Bintuni'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kabupaten Teluk Wondama'],
            ['id_provinsi' => 33, 'nama_kabupaten_kota' => 'Kota Sorong'],

            // Papua
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Biak Numfor'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Jayapura'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Keerom'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Kepulauan Yapen'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Mamberamo Raya'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Sarmi'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Supiori'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kabupaten Waropen'],
            ['id_provinsi' => 34, 'nama_kabupaten_kota' => 'Kota Jayapura'],

            // Papua Selatan
            ['id_provinsi' => 35, 'nama_kabupaten_kota' => 'Kabupaten Asmat'],
            ['id_provinsi' => 35, 'nama_kabupaten_kota' => 'Kabupaten Boven Digoel'],
            ['id_provinsi' => 35, 'nama_kabupaten_kota' => 'Kabupaten Mappi'],
            ['id_provinsi' => 35, 'nama_kabupaten_kota' => 'Kabupaten Merauke'],

            // Papua Tengah
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Deiyai'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Dogiyai'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Intan Jaya'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Mimika'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Nabire'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Paniai'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Puncak'],
            ['id_provinsi' => 36, 'nama_kabupaten_kota' => 'Kabupaten Puncak Jaya'],

            // Papua Pegunungan
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Jayawijaya'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Lanny Jaya'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Mamberamo Tengah'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Nduga'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Pegunungan Bintang'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Tolikara'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Yahukimo'],
            ['id_provinsi' => 37, 'nama_kabupaten_kota' => 'Kabupaten Yalimo'],

            // Papua Barat Daya
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kabupaten Maybrat'],
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kabupaten Raja Ampat'],
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kabupaten Sorong'],
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kabupaten Sorong Selatan'],
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kabupaten Tambrauw'],
            ['id_provinsi' => 38, 'nama_kabupaten_kota' => 'Kota Sorong'],
            // Tambahkan data kabupaten/kota lainnya dari provinsi lain di sini
        ];

        foreach ($kabupatenKota as $kabupatenKota) {
            KabupatenKota::create($kabupatenKota);
        }
    }
}
